baseurl: /
url: https://cookiemonsternz.github.io/blog

title: mulid
description: "A custom dark / light theme, inspired by the one dark theme, for use in my personal sites"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  hard_wrap: false
  math_engine: mathjax